---
version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:latest
    #image: freqtradeorg/freqtrade:2022.6
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
     context: .
     dockerfile: "./Dockerfile.mark"
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade_deadzone
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "8081:8081"
      - "8080:8080"
    # Default command used when running `docker compose up`

    command: >
      trade -s deadzone -c user_data/config.json